basePath: /
host: localhost:8001
info:
  contact:
    email: tropanartov@yandex.ru
    name: API Support
  description: REST API для мобильного приложения "Тропа Нартов"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Tropa Nartov API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: 'Введите токен в формате: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
